// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type ExchangesRate struct {
	ID         int64
	Code       sql.NullString
	CodeUn     sql.NullString
	Name       sql.NullString
	High       sql.NullString
	Low        sql.NullString
	VarBid     sql.NullString
	PctChange  sql.NullString
	Bid        sql.NullString
	Ask        sql.NullString
	Timestamp  sql.NullString
	CreateDate sql.NullString
}
